[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
libc = "0.2.171"
serde = { version = "1.0.219", features = ["derive"] }
ron = "0.9.0"
serde_json = "1.0.140"